<a href="https://colab.research.google.com/github/AliMO77/hello-world/blob/master/doorCleaner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Alhamdulilah1234!
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#RETRACT FORWARD

In [ ]:
import pandas as pd
import numpy as np
import datetime
from matplotlib import pyplot as plt

rf = pd.read_csv('/content/drive/MyDrive/PaulWurth/RetractForward.csv', sep=";",skiprows=1,header=None)

def make_df(my_csv):
  df = pd.DataFrame(my_csv)
  df.columns=['index','TimeStamp','Value','quality']
  df = df.drop(['index','quality'],axis=1)
  df.TimeStamp= pd.to_datetime(df.TimeStamp)
  return df

RetractForwardo = make_df(rf)

RetractForward = RetractForwardo.iloc[150:165].copy()
RetractForward.index = np.arange(len(RetractForward))

# RetractForward = RetractForwardo.iloc[154:175].copy()
# RetractForward.index = np.arange(len(RetractForward))

# RetractForward = RetractForwardo.iloc[154:161].copy()
# RetractForward.index = np.arange(len(RetractForward))

# RetractForward = RetractForwardo.iloc[161:166].copy()
# RetractForward.index = np.arange(len(RetractForward))

# RetractForward = RetractForwardo.iloc[150:166].copy()
# RetractForward.index = np.arange(len(RetractForward))
# plt.figure(figsize=(35,10))
# plt.plot(RetractForward['Value'])

RetractForward['diff']= RetractForward['Value'].round().diff()
mninValueIndex = RetractForward['Value'].round().idxmin()
minDiffer = RetractForward.iloc[mninValueIndex]['diff']

if((minDiffer < 0) and (minValue < 10)):
    print("sup")

In [ ]:
RetractForward

                   TimeStamp       Value   diff
0  2021-09-02 05:39:03+02:00    1.036067    NaN
1  2021-09-02 05:39:07+02:00    1.036067    0.0
2  2021-09-02 05:39:11+02:00    1.036067    0.0
3  2021-09-02 05:39:15+02:00  376.923035  376.0
4  2021-09-02 05:39:19+02:00  376.923035    0.0
5  2021-09-02 05:39:23+02:00  376.923035    0.0
6  2021-09-02 05:39:27+02:00  376.923035    0.0
7  2021-09-02 05:39:31+02:00  145.530600 -231.0
8  2021-09-02 05:39:35+02:00  145.530600    0.0
9  2021-09-02 05:39:39+02:00  145.530600    0.0
10 2021-09-02 05:39:43+02:00  145.530600    0.0
11 2021-09-02 05:39:47+02:00    1.075723 -145.0
12 2021-09-02 05:39:51+02:00    1.075723    0.0
13 2021-09-02 05:39:55+02:00    1.075723    0.0
14 2021-09-02 05:39:59+02:00    1.075723    0.0

In [ ]:
def getEnd(timeseries):
     try:      
      timeseries['diff']= timeseries['Value'].round().diff()
      mninValueIndex = timeseries['Value'].round().idxmin()
      minValue =  timeseries.iloc[mninValueIndex]['Value']
      minDiffer = timeseries.iloc[mninValueIndex]['diff']
      time = timeseries.iloc[mninValueIndex]['TimeStamp']
      
      if(time and (minDiffer < 0) and (minValue < 10)):
        end = time
        return end
      else:
        return 0
     except IndexError:
        return 0
   
end = getEnd(RetractForward)
end

Timestamp('2021-09-02 05:39:47+0200', tz='pytz.FixedOffset(120)')

In [ ]:
def getStart(timeseries):
     try:      
      timeseries['diff']= timeseries['rolling_mean'].diff()
      conditionOne = timeseries[timeseries['diff']>0]
      firstIndex = conditionOne.index[0]
      time = timeseries.iloc[firstIndex-1]['TimeStamp']

      if(time):
        start = time
        return start
      else:
        return 0
     except IndexError:
        return 0
   
start = getStart(RetractForward)
start

Timestamp('2021-09-02 05:39:11+0200', tz='pytz.FixedOffset(120)')

#LOWER RAISE

In [ ]:
import pandas as pd
import numpy as np
import datetime
from matplotlib import pyplot as plt

rf = pd.read_csv('/content/drive/MyDrive/PaulWurth/LowerRaise.csv', sep=";",skiprows=1,header=None)

def make_df(my_csv):
  df = pd.DataFrame(my_csv)
  df.columns=['index','TimeStamp','Value','quality']
  df = df.drop(['index','quality'],axis=1)
  df.TimeStamp= pd.to_datetime(df.TimeStamp)
  return df

LowerRaise = make_df(rf)
LowerRaise.loc[LowerRaise['Value']<30,'Value'] = 0
# RetractForward = RetractForwardo.iloc[150:158].copy()
# RetractForward.index = np.arange(len(RetractForward))

# RetractForward = RetractForwardo.iloc[154:175].copy()
# RetractForward.index = np.arange(len(RetractForward))

# RetractForward = RetractForwardo.iloc[154:161].copy()
# RetractForward.index = np.arange(len(RetractForward))

# RetractForward = RetractForwardo.iloc[161:166].copy()
# RetractForward.index = np.arange(len(RetractForward))

# LowerRaise = LowerRaise.iloc[8:24].copy()
# LowerRaise.index = np.arange(len(LowerRaise))
plt.figure(figsize=(35,10))
plt.plot(LowerRaise['Value'])
LowerRaise

In [ ]:
def getEndNumpy(timeseries):
     try:      
      check = 0
      timeseries.loc[timeseries['value']<50,'value'] = 0
      timeseries['diff']= timeseries['value'].round().diff().fillna(0)

      differences = timeseries['diff'].astype(int)
      values = timeseries['value'].astype(int)

      a = np.where(differences<0)
      b = np.where(values == min(values))
     
      endIndex = np.intersect1d(a, b)
      time = timeseries.iloc[endIndex[0]]['time']
      
      if(time and (min(values) < 5)):
        end = time
        check = 1
        return end,check
      else:
        return 0,check
     except IndexError:
        return 0,check

In [ ]:
def getStartNumpy(timeseries):
     try: 
      check = 0     
      timeseries.loc[timeseries['value']<50,'value'] = 0
      timeseries['diff']= timeseries['value'].round().diff().fillna(0)      
      differences = timeseries['diff'].astype(int)
      values = timeseries['value'].astype(int)

      a = np.where(differences>0)
      a = np.add(a,-1)
      b = np.where(values == min(values))
      
      startIndex = np.intersect1d(a, b)
      time = timeseries.iloc[startIndex[0]]['time']
      
      if(time and (min(values) < 50)):
        end = time
        check = 1
        return end,check
      else:
        return 0,check
     except IndexError:
        return 0,check

In [ ]:
import pandas as pd
import numpy as np
import datetime
from matplotlib import pyplot as plt
bw= pd.read_csv('/content/drive/MyDrive/PaulWurth/WeirdWeight.csv', sep=";",skiprows=1,header=None)

def make_df(my_csv):
  df = pd.DataFrame(my_csv)
  df.columns=['index','time','value','quality']
  df = df.drop(['index','quality'],axis=1)
  df.time= pd.to_datetime(df.time)
  return df

weight = make_df(bw)
weight.columns= ['time','value']
weight['value'] = weight['value'].round()
weight

In [ ]:
start = getStartNumpy(weight)
end = getEndNumpy(weight)
start , end

(0, 0)

In [ ]:
weight['rolling']= weight['value'].round().rolling(window = 3).mean().fillna(0)
weight['diff']= weight['rolling'].round().diff().fillna(0)    
differences = weight['diff'].astype(int)
values = weight['rolling'].astype(int)

a = np.where(differences<0)
b = np.where(values == min(values))

startIndex = np.intersect1d(a, b)
time = weight.iloc[startIndex[0]]['time']
time

In [ ]:
plt.figure(figsize=(35,10))
plt.plot(weight['rolling'])

In [ ]:
import pandas as pd
import numpy as np
import datetime
from matplotlib import pyplot as plt

rf1 = pd.read_csv('/content/drive/MyDrive/PaulWurth/RF1.csv', sep=";",skiprows=1,header=None)
rf2 = pd.read_csv('/content/drive/MyDrive/PaulWurth/RF2.csv', sep=";",skiprows=1,header=None)


def make_df(my_csv):
  df = pd.DataFrame(my_csv)
  df.columns=['index','time','value','quality']
  df = df.drop(['index','quality'],axis=1)
  df.time= pd.to_datetime(df.time)
  return df

Rf1 = make_df(rf1)
Rf1.columns= ['time','value']

Rf2 = make_df(rf2)
Rf1.columns= ['time','value']

Rf1.iloc[8:70]

In [ ]:
start, check = getStartNumpy(Rf1)
end, check2= getEndNumpy(Rf1)
start

In [ ]:
Rf1[:30]

#Charging

In [ ]:
def getEndNumpy(timeseries):
     try:      
      check = 0
    
      timeseries.loc[timeseries['value']<1,'value'] = 0
      timeseries['rolling']= timeseries['value'].rolling(window = 5).mean() 
      timeseries['diff']= timeseries['rolling'].round().diff().fillna(0)     

      differences = timeseries['diff'].astype(int)
      values = timeseries['value'].astype(int)

      a = np.where(differences<0)
      b = np.where(values == min(values))
     
      endIndex = np.intersect1d(a, b)
      time = timeseries.iloc[endIndex[-1]-3]['time']
      
      if(time and (min(values) < 5)):
        end = time
        check = 1
        return end,endIndex
      else:
        return 0,check
     except IndexError:
        return 0,check

def getStartNumpy(timeseries):
     try: 
      check = 0     
      timeseries.loc[timeseries['value']<1,'value'] = 0
      timeseries['rolling']= timeseries['value'].rolling(window = 5).mean() 
      timeseries['diff']= timeseries['rolling'].round().diff().fillna(0)      
      differences = timeseries['diff'].astype(int)
      values = timeseries['value'].astype(int)

      a = np.where(differences>0)
      a = np.add(a,-1)
      b = np.where(values == min(values))
      
      startIndex = np.intersect1d(a, b)
      time = timeseries.iloc[startIndex[0]]['time']
      
      if(time and (min(values) < 50)):
        end = time
        check = 1
        return end,check
      else:
        return 0,check
     except IndexError:
        return 0,check

#Travelling

In [ ]:
def getStart2(timeseries):
     try: 
      check = 0     
      timeseries.loc[timeseries['value']<1,'value'] = 0
      timeseries['rolling']= timeseries['value'].rolling(window = 7).mean() 
      timeseries['diff']= timeseries['rolling'].round().diff().fillna(0)      
      differences = timeseries['diff'].astype(int)
      values = timeseries['value'].astype(int)

      a = np.where(differences>0)
      a = np.add(a,-1)
      b = np.where(values == min(values))
      
      startIndex = np.intersect1d(a, b)
      time = timeseries.iloc[startIndex[0]]['time']
      
      if(time and (min(values) < 50)):
        end = time
        check = 1
        return end,check
      else:
        return 0,check
     except Exception as e:
        return 0,check

def getStart(timeseries):

In [73]:
import pandas as pd
import numpy as np
import datetime
from matplotlib import pyplot as plt

chr = pd.read_csv('/content/drive/MyDrive/PaulWurth/fff/TVL.csv', sep=";",skiprows=1,header=None)


def make_df(my_csv):
  df = pd.DataFrame(my_csv)
  df.columns=['index','time','value','quality']
  df = df.drop(['index','quality'],axis=1)
  df.time= pd.to_datetime(df.time)
  return df

tvl = make_df(chr)
tvl.columns= ['time','value']

tvl['value'] = tvl['value'].round()
tvl['diffr']= tvl['value'].rolling(window = 4).mean().diff().fillna(0).round()
tvl.drop(tvl[(tvl.diffr <= 10 ) & (tvl.diffr > 0)].index, inplace=True,axis= 'index')

times = []
starts = []
ends =[]
distances=[]

In [74]:
def getTime(timeseries):
  while(len(timeseries)>0):
    try : 
      value = timeseries.iloc[timeseries[timeseries.diffr != 0].index[0]]['diffr']

      #if value > 0:
      start = timeseries.iloc[timeseries[timeseries.diffr != 0].index[0]]['time']
      startValue = timeseries.iloc[timeseries[timeseries.diffr != 0].index[0]]['value']

      timeseries.drop(timeseries[timeseries.time <= start].index, inplace=True,axis= 'index')
      timeseries.reset_index(drop=True, inplace=True)

      firstzero = (timeseries[timeseries.diffr == 0].index[0])
      index = firstzero - 3
      end =  timeseries.iloc[index].time
      endValue =  timeseries.iloc[index].value

      timeseries.drop(timeseries[timeseries.index <= firstzero].index, inplace=True,axis= 'index')
      timeseries.reset_index(drop=True, inplace=True)

      time = (end-start).total_seconds()
      distance = abs(endValue-startValue)
      times.append(time)
      starts.append(start)
      ends.append(end)
      distances.append(distance)

      #starts.append(str(start)+':'+str(end))
    
    except Exception as e:
      return sum(times), starts[0],ends[-1],sum(distances)
      break

In [75]:
time,start,end,distance = getTime(tvl)
time,start,end,distance

(46305.0,
 Timestamp('2021-11-05 00:39:17+0100', tz='pytz.FixedOffset(60)'),
 Timestamp('2021-11-05 04:43:59+0100', tz='pytz.FixedOffset(60)'),
 809733.0)

In [76]:
firstzero = (tvl[tvl.diffr == 0].index[0])
index = firstzero - 3
end =  tvl.iloc[index].time
endValue =  tvl.iloc[index].value
# tvl.drop(tvl[tvl.index <= firstzero].index, inplace=True,axis= 'index')
# tvl.reset_index(drop=True, inplace=True)
end

Timestamp('2021-11-05 05:23:52+0100', tz='pytz.FixedOffset(60)')

In [77]:
tvl[0:30]

                        time    value  diffr
0  2021-11-05 04:44:07+01:00  46500.0    0.0
1  2021-11-05 04:44:08+01:00  46500.0    0.0
2  2021-11-05 04:44:09+01:00  46500.0    0.0
3  2021-11-05 04:44:10+01:00  46500.0    0.0
4  2021-11-05 04:44:11+01:00  46500.0    0.0
5  2021-11-05 04:44:12+01:00  46500.0    0.0
6  2021-11-05 04:44:13+01:00  46500.0    0.0
7  2021-11-05 04:44:14+01:00  46500.0    0.0
8  2021-11-05 04:44:15+01:00  46500.0    0.0
9  2021-11-05 04:44:16+01:00  46500.0    0.0
10 2021-11-05 04:44:17+01:00  46500.0    0.0
11 2021-11-05 04:44:18+01:00  46500.0    0.0
12 2021-11-05 04:44:19+01:00  46500.0    0.0
13 2021-11-05 04:44:20+01:00  46500.0    0.0
14 2021-11-05 04:44:21+01:00  46500.0    0.0
15 2021-11-05 04:44:22+01:00  46500.0    0.0
16 2021-11-05 04:44:23+01:00  46500.0    0.0
17 2021-11-05 04:44:24+01:00  46500.0    0.0
18 2021-11-05 04:44:25+01:00  46500.0    0.0
19 2021-11-05 04:44:26+01:00  46500.0    0.0
20 2021-11-05 04:44:27+01:00  46500.0    0.0
21 2021-11-05 04:44:28+01:00  46500.0    0.0
22 2021-11-05 04:44:29+01:00  46500.0    0.0
23 2021-11-05 04:44:30+01:00  46500.0    0.0
24 2021-11-05 04:44:31+01:00  46500.0    0.0
25 2021-11-05 04:44:32+01:00  46500.0    0.0
26 2021-11-05 04:44:33+01:00  46500.0    0.0
27 2021-11-05 04:44:34+01:00  46500.0    0.0
28 2021-11-05 04:44:35+01:00  46500.0    0.0
29 2021-11-05 04:44:36+01:00  46500.0    0.0